import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
WEB_DIR = ROOT / "web"


class FrontendSmokeTests(unittest.TestCase):
    def test_index_loads_frontend_modules(self):
        html = (WEB_DIR / "index.html").read_text(encoding="utf-8")
        self.assertIn("ui-foundation.js", html)
        self.assertIn("app-auth.js", html)
        self.assertIn("app-routing.js", html)
        self.assertIn("app.js", html)

    def test_frontend_modules_export_expected_globals(self):
        auth_js = (WEB_DIR / "app-auth.js").read_text(encoding="utf-8")
        routing_js = (WEB_DIR / "app-routing.js").read_text(encoding="utf-8")
        foundation_js = (WEB_DIR / "ui-foundation.js").read_text(encoding="utf-8")
        self.assertIn("window.CRMAppAuth", auth_js)
        self.assertIn("window.CRMAppRouting", routing_js)
        self.assertIn("window.CRMUI", foundation_js)
        app_js = (WEB_DIR / "app.js").read_text(encoding="utf-8")
        self.assertIn("consumePostLoginNotice", app_js)
        self.assertIn('"/api/auth_request_access_help"', app_js)

    def test_bank_branding_does_not_depend_on_remote_clearbit_logos(self):
        app_js = (WEB_DIR / "app.js").read_text(encoding="utf-8")
        self.assertNotIn("logo.clearbit.com", app_js)

    def test_standalone_login_fallback_yields_to_app_auth(self):
        html = (WEB_DIR / "index.html").read_text(encoding="utf-8")
        self.assertIn("if (window.__APP_JS_LOADED && window.CRMAppAuth)", html)
        guard_pos = html.index("if (window.__APP_JS_LOADED && window.CRMAppAuth)")
        prevent_pos = html.index("event.preventDefault();", guard_pos)
        self.assertLess(guard_pos, prevent_pos)

    def test_login_sets_role_route_before_app_init(self):
        auth_js = (WEB_DIR / "app-auth.js").read_text(encoding="utf-8")
        route_pos = auth_js.index('params.set("holding", "1");')
        init_pos = auth_js.index("await deps.init();", route_pos)
        self.assertLess(route_pos, init_pos)
        self.assertIn('localStorage.getItem("crm.currentWorkspaceId")', auth_js)
        self.assertIn('"/api/auth_request_access_recovery"', auth_js)
        self.assertIn('"crm.postLoginAccessWarning"', auth_js)
        self.assertIn("Recuperar acceso", auth_js)

    def test_visible_service_cards_keep_click_and_href_invariants(self):
        app_js = (WEB_DIR / "app.js").read_text(encoding="utf-8")
        self.assertIn('coreCards.addEventListener("click", (event) => {', app_js)
        self.assertIn("const fallbackNavigate = () => {", app_js)
        self.assertIn('card.dataset.action = "crm-inmo";', app_js)
        self.assertIn('card.dataset.action = "crm-gestoria";', app_js)
        self.assertIn('card.dataset.action = "crm-seguros";', app_js)
        self.assertIn('card.dataset.action = "crm-fin";', app_js)
        self.assertIn('data-action="crm-inmo"', app_js)
        self.assertIn('data-action="crm-gestoria"', app_js)
        self.assertIn('data-action="crm-seguros"', app_js)
        self.assertIn('data-action="crm-fin"', app_js)

    def test_visible_home_cards_match_permission_guards(self):
        app_js = (WEB_DIR / "app.js").read_text(encoding="utf-8")
        self.assertIn("const hasAdminWideAccess = (user) => {", app_js)
        self.assertIn("const canAccessSharedHomeModules = (user) => hasAdminWideAccess(user);", app_js)
        self.assertIn("if (hasAdminWideAccess(user)) return true;", app_js)
        self.assertIn("const isPriv = hasAdminWideAccess(user);", app_js)
        self.assertIn("const canManageWorkspace = Boolean(user && hasAdminWideAccess(user));", app_js)
        self.assertIn('if (!userCanAccessService("inmobiliaria")) return;', app_js)
        self.assertIn('if (!userCanAccessService("gestoria")) return;', app_js)
        self.assertIn('if (!userCanAccessService("seguros")) return;', app_js)
        self.assertIn('if (!userCanAccessService("financiaciones")) return;', app_js)
        self.assertIn("const openWorkspaceQuickAccessFromCompanyCard = (empresaName = \"\") => {", app_js)
        self.assertIn("if (name && openWorkspaceQuickAccessFromCompanyCard(name)) {", app_js)

    def test_workspace_copilot_includes_process_supervisor_feed(self):
        app_js = (WEB_DIR / "app.js").read_text(encoding="utf-8")
        self.assertIn("Chat interno", app_js)
        self.assertIn('id="workspaceInternalCopilotFeed"', app_js)
        self.assertIn('id="workspaceInternalCopilotForm"', app_js)
        self.assertIn('root.id = "globalInternalCopilotWidget"', app_js)
        self.assertIn('id="globalInternalCopilotToggle"', app_js)
        self.assertIn('id="globalInternalCopilotPanel"', app_js)
        self.assertIn('id="globalInternalCopilotFeed"', app_js)
        self.assertIn('id="globalInternalCopilotForm"', app_js)
        self.assertIn('data-global-copilot-quick="briefing"', app_js)
        self.assertIn('data-global-copilot-quick="current_entity"', app_js)
        self.assertIn('data-global-copilot-quick="close_loop"', app_js)
        self.assertIn('data-global-copilot-mode="operator"', app_js)
        self.assertIn('data-global-copilot-mode="supervisor"', app_js)
        self.assertIn('data-global-copilot-mode="direccion"', app_js)
        self.assertIn('data-global-copilot-mode="legal"', app_js)
        self.assertIn('data-global-copilot-quick="close_loop"', app_js)
        self.assertIn('data-global-copilot-quick="platform"', app_js)
        self.assertIn('data-global-copilot-suggest="continúa con lo de esta mañana"', app_js)
        self.assertIn('"/api/internal_copilot_chat"', app_js)
        self.assertIn('"/api/internal_copilot_action"', app_js)
        self.assertIn("Opciones avanzadas", app_js)
        self.assertIn("El asistente decide el proceso y resuelve el trabajo por detrás.", app_js)
        self.assertIn("Pídeme el trabajo tal como lo harías a una persona", app_js)
        self.assertIn("current_client_id", app_js)
        self.assertIn("current_seguro_id", app_js)
        self.assertIn("current_renta_entry_id", app_js)
        self.assertIn("current_hipoteca_id", app_js)
        self.assertIn("current_factura_id", app_js)
        self.assertIn("current_rrhh_document_id", app_js)
        self.assertIn("current_persona_id", app_js)
        self.assertIn("current_community_id", app_js)
        self.assertIn("current_workspace_name", app_js)
        self.assertIn("current_workspace_company_name", app_js)
        self.assertIn("renderWorkspaceInternalCopilotFeed", app_js)
        self.assertIn('name="attachment"', app_js)
        self.assertIn("multiple", app_js)
        self.assertIn("Supervisor de procesos", app_js)
        self.assertIn('id="workspaceProcessSupervisorFeed"', app_js)
        self.assertIn('id="workspaceProcessSupervisorHistory"', app_js)
        self.assertIn('data-copilot-process-action', app_js)
        self.assertIn('data-copilot-assistant-action', app_js)
        self.assertIn('"/api/internal_copilot_action"', app_js)
        self.assertIn("bulk_revalidate_processes", app_js)
        self.assertIn("bulk_safe_repair", app_js)
        self.assertIn("bulk_rerun_facturas_ocr", app_js)
        self.assertIn("resolve_domain_safe", app_js)
        self.assertIn("autorreview_domain", app_js)
        self.assertIn("autorreview_global", app_js)
        self.assertIn("daily_review_agenda", app_js)
        self.assertIn("maybePrimeWorkspaceInternalCopilotAgenda", app_js)
        self.assertIn("ensurePersistentInternalCopilotWidget", app_js)
        self.assertIn("submitInternalCopilotQuery", app_js)
        self.assertIn("collectInternalCopilotContext", app_js)
        self.assertIn("persistentInternalCopilotOpen", app_js)
        self.assertIn("crm.persistentInternalCopilotVisible.v4", app_js)
        self.assertIn("currentWorkspaceCopilotAgendaKey", app_js)
        self.assertIn("currentWorkspaceCopilotPrimeKey", app_js)
        self.assertIn("currentWorkspaceCopilotAgendaLoading", app_js)
        self.assertIn("auto_daily_agenda: true", app_js)
        self.assertIn("auto_prime_console: true", app_js)
        self.assertIn("void maybePrimeWorkspaceInternalCopilotAgenda()", app_js)
        self.assertIn('data-global-copilot-suggest="diagnostica la ficha actual"', app_js)
        self.assertIn("prime_operator_console", app_js)
        self.assertIn("close_loop_safe", app_js)
        self.assertIn("set_copilot_mode", app_js)
        self.assertIn("mode_switch", app_js)
        self.assertIn("setPersistentInternalCopilotMode", app_js)
        self.assertIn("persistentInternalCopilotMode", app_js)
        self.assertIn("start_review_queue", app_js)
        self.assertIn("continue_review_queue", app_js)
        self.assertIn("revalidate_current_and_continue", app_js)
        self.assertIn("post_actions", app_js)
        self.assertIn("refresh_supervisor", app_js)
        self.assertIn("Array.isArray(result?.actions)", app_js)
        self.assertIn("Array.isArray(result?.cards)", app_js)
        self.assertIn('"/api/workspace_process_supervisor_ack"', app_js)
        self.assertIn('"/api/workspace_process_supervisor_action"', app_js)
        self.assertIn("reload_dashboard_block", app_js)
        self.assertIn("reload_records", app_js)
        self.assertIn("refresh_client_summary", app_js)
        self.assertIn("revalidate_process", app_js)
        self.assertIn("state.pendingClienteOpen", app_js)
        self.assertIn("loadGestoriaDashboardDocumentos({ force: true })", app_js)
        self.assertIn("loadGestoriaDashboardContabilidad({ force: true })", app_js)
        self.assertIn("loadGestoriaDashboardGestiones({ force: true })", app_js)
        self.assertIn("loadGestoriaRentaDashboard({ force: true })", app_js)
        self.assertIn("loadGestoriaContabilidad()", app_js)
        self.assertIn("loadGestoriaFact()", app_js)
        self.assertIn("Ficha cliente refrescada", app_js)
        self.assertIn("Proceso validado", app_js)
        self.assertIn("OCR relanzado", app_js)
        self.assertIn("handleProcessSupervisorResponse", app_js)
        self.assertIn("loadWorkspaceProcessSupervisorHistory", app_js)

    def test_gitignore_covers_local_runtime_artifacts(self):
        gitignore = (ROOT / ".gitignore").read_text(encoding="utf-8")
        self.assertIn("data/*.bak_*", gitignore)
        self.assertIn("*.sqlite-wal", gitignore)
        self.assertIn("__pycache__/", gitignore)


if __name__ == "__main__":
    unittest.main()
